<a href="https://colab.research.google.com/github/GoliShreyaReddy/ML_ICP3_700763884/blob/main/Copy_of_Shreyareddygoli_ML_ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a)

In [ ]:
import numpy as np

# Step 1: Create a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)

# Step 2: Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)

# Step 3: Print the shape of the reshaped array
array_shape = reshaped_array.shape
print(f"Shape of the reshaped array: {array_shape}")

# Step 4: Replace the maximum value in each row by 0
for row in reshaped_array:
    # Find the maximum value in the row
    max_value = row.max()
    # Replace the maximum value with 0
    row[row == max_value] = 0

print("Array after replacing the maximum value in each row with 0:")
print(reshaped_array)

# Step 5: Create a 2-dimensional array of size 4x3 composed of 4-byte integer elements
array_4x3 = np.zeros((4, 3), dtype=np.int32)

# Step 6: Print the shape, type, and data type of the 4x3 array
shape_4x3 = array_4x3.shape
type_4x3 = type(array_4x3)
dtype_4x3 = array_4x3.dtype

print(f"Shape of the 4x3 array: {shape_4x3}")
print(f"Type of the 4x3 array: {type_4x3}")
print(f"Data type of the 4x3 array: {dtype_4x3}")


Shape of the reshaped array: (3, 5)
Array after replacing the maximum value in each row with 0:
[[15  1  0  1 12]
 [ 0  5  8  4 13]
 [ 6  0  6  8 11]]
Shape of the 4x3 array: (4, 3)
Type of the 4x3 array: <class 'numpy.ndarray'>
Data type of the 4x3 array: int32


b)

In [ ]:
import numpy as np

# Define the square array
matrix = np.array([[3, -2],
                   [1,  0]])

# Compute the eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Print the eigenvalues and right eigenvectors
print("Eigenvalues:")
print(eigenvalues)
print("\nRight Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[2. 1.]

Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


c)

In [ ]:
import numpy as np

# Define the given array
array = np.array([[0, 1, 2],
                  [3, 4, 5]])

# Extract the diagonal elements
diagonal_elements = np.diagonal(array)

# Compute the sum of the diagonal elements
sum_diagonal = diagonal_elements.sum()

# Print the sum of the diagonal elements
print("Sum of the diagonal elements:")
print(sum_diagonal)


Sum of the diagonal elements:
4


d)

In [ ]:
import numpy as np

# Define the original array with shape 3x2
array_3x2 = np.array([[1, 2],
                      [3, 4],
                      [5, 6]])

# Reshape the array to 2x3
array_2x3 = array_3x2.reshape(2, 3)

# Print both arrays
print("Original array (3x2):")
print(array_3x2)

print("\nReshaped array (2x3):")
print(array_2x3)


Original array (3x2):
[[1 2]
 [3 4]
 [5 6]]

Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]
